package com.deardogbit.backend.dao;

import com.deardogbit.backend.entity.TmpUser;
import com.deardogbit.backend.entity.TmpUserExample;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TmpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_user
     *
     * @mbggenerated
     */
    int countByExample(TmpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_user
     *
     * @mbggenerated
     */
    int insert(TmpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_user
     *
     * @mbggenerated
     */
    int insertSelective(TmpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_user
     *
     * @mbggenerated
     */
    TmpUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TmpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TmpUser record);
}