server:
 port: ${SERVER_PORT}
 ssl:
  key-store: classpath:3951114_www.deardogbit.com.pfx
  key-store-password: 2d2buk2O
  key-store-type: PKCS12
  key-alias: 1

spring:
  datasource:
    name: deadogbit
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/deardogbit?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: ${DB_PW}

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml